"""add_fragrance_url_unique_index

Revision ID: b04fc1803860
Revises: 047726f474ed
Create Date: 2025-09-16 21:11:36.451499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b04fc1803860'
down_revision: Union[str, Sequence[str], None] = '047726f474ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("fragrances", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_fragrance_url", ["url"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('top_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('middle_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('perfumer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_ratings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('api_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fragrances_pkey'))
    )
    with op.batch_alter_table('fragrances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fragrances_id'), ['id'], unique=False)

    # ### end Alembic commands ###
